[package]
name = "macos-xbar-commands"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "macos-resize-dock",
    "macos-toggle-dark-mode",
    "macos-toggle-dock",
    "macos-toggle-natural-scrolling",
    # "macos-invert-natural-scrolling",
]

[dependencies]
