[package]
name = "macos-xbar-commands"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cc = "1.0"

[target.'cfg(target_os = "macos")'.dependencies]
tempfile = "3.23.0"

[dependencies]
thiserror = "2.0.17"
clap = { version = "4.5", features = ["derive"] }
