[package]
name = "macos-invert-natural-scrolling"
version = "0.1.0"
edition = "2024"

[dependencies]
accessibility-sys = "0.1"
cocoa = "0.25"
objc = "0.2"
core-foundation = "0.9"

thiserror = "2.0.17"

[features]
cargo-clippy = [] # Needed by objc crate to use conditional macros
