[package]
name = "macos-toggle-dock"
version = "0.1.0"
edition = "2021"

[package.metadata]
include = ["toggle-dock.sh"]

[dependencies]
thiserror = "2.0.17"
clap = { version = "4.5", features = ["derive"] }
